Repository PoCInnovation/InterPlanetaryCloud, pull requests merged in 2023-01, with the labels that each got.

#114 ESLint action optimized
  .github/workflows/eslint-tests.yaml
Labels: enhancement

#113 [Feature]: add providers & update sdk
  CONTRIBUTING.md
  Dockerfile
  cypress/e2e/features/files.cy.ts
  docker-compose.yml
  next.config.js
  package.json
  pages/login.tsx
  src/components/contact/AddContact.tsx
  src/components/file/UpdateContentFile.tsx
  src/components/file/UploadFile.tsx
  src/components/file/detailsFile/DetailsFile.tsx
  src/components/file/detailsFile/DrawerDetailsFile.tsx
  src/globals.d.ts
  src/lib/auth.ts
  src/lib/computing.ts
  src/lib/contact.ts
  src/lib/drive.ts
  src/lib/services/deploy.ts
  src/lib/user.ts
  src/types/types.ts
  src/utils/fileManipulation.ts
  yarn.lock
Labels: enhancement

#117 fix: incomplete github repositories list into modal
  pages/api/computing/github/repositories.ts
  src/components/computing/github/GithubModal.tsx
  src/types/types.ts
Labels: bug

#119 build(deps): yarn.lock dependencies upgraded
  yarn.lock
Labels: dependencies
